version: '3.8'
services:
  server:
    container_name: basic-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      # - postgres
      - redis-container
    env_file:
      - .env
    networks:
      - common-network

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   restart: always
  #   ports:
  #     - ${DATABASE_PORT}:5432
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/www/vls/postgres:/var/lib/postgresql/data

  redis-container:
    image: redis
    restart: always
    volumes:
      # - /var/www/basic/redis:/data
      - F:/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
